name: git-hygiene

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main, master]
  workflow_dispatch:

jobs:
  git-hygiene:
    uses: saagpatel/sovereign/.github/workflows/git-hygiene.yml@331b472c4ccebba09cf3f169e5fc6dca900ea571
