name: perf-foundation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main, master]
  workflow_dispatch:

jobs:
  perf-foundation:
    uses: saagpatel/sovereign/.github/workflows/perf-foundation.yml@331b472c4ccebba09cf3f169e5fc6dca900ea571
